## CS559: Homework #1
Jerry Cheng

Assignment #1: due on **2/23/2021 by 11:59 PM**. 
- Change the file name as *YourName*_S21_CS559_HW1
- Submit the assignment both in format of *ipynb* and *html*. 
    - You can export the file as *html* as `File`>`Download as`>`HTML`. The assignment should be own work and must not be shared between classmates. 
- You **do not need to compress** the files. You can submit individual files.
- This assignment focuses on two topics - linear algebra and data pre-processing. 
    - For linear algebra questions, when the question says "implement", you cannot use any built-in functions.
- This assignment should an individual work. Do not collaborate with classmates or get help from 3rd person. You may surf internet if you need to. Then site the reference. 

### Problem 1 [10 pts]
- Implement a function `dot_product` to calculate the dot product of two 1 by n arrays. [6 pts] 
```
a = array([1, 2, 3, 4])
b = array([2, 3, 4, 5])
dot_product(a,b) = 40
```

In [4]:
### Code Starts Here
def dot_product(a,b):
    if(a.size != b.size): raise Exception("Error: array a must be the same length as array b.")
        
    answer = 0
    for num1,num2 in zip(a, b):
        answer += (num1 * num2)
    
    return answer;
        
    

- Test your code after generating two random 1 by 10 arrays. [4 pts]


In [24]:
### Code Starts Here
import numpy as np
answer = 0

array1 = np.random.randint(1,10,10);
array2 = np.random.randint(1,10,10);

#print('Array 1: ',array1, 'Array 2: ', array2)
print(dot_product(array1, array2))

207


### Problem 2 [10 pts]
- Consider three vectors ${\bf x}_1=(1,3), {\bf x}_2=(-1,5)$, and ${\bf x}_3=(0,7)$. Find the distance of each point from the **origin**. [4 pts]

In [25]:
### Code Starts Here
import math
# Assuming that the origin is simply (0,0)

print("Distance from x1 to the origin: ", math.sqrt((math.pow(1, 2) + math.pow(3, 2))))
print("Distance from x2 to the origin: ", math.sqrt((math.pow(-1, 2) + math.pow(5, 2))))
print("Distance from x3 to the origin: ", math.sqrt((math.pow(0, 2) + math.pow(7, 2))))

Distance from x1 to the origin:  3.1622776601683795
Distance from x2 to the origin:  5.0990195135927845
Distance from x3 to the origin:  7.0


- Rotate the coordinates by 35 degress in counter clockwise. [4 pts]

In [26]:
### Code Starts Here
import math

def rotateCCdegrees(x, y, angle):
    angle = math.radians(angle)
    newx = (x * math.cos(angle)) - (y * math.sin(angle))
    newy = (x * math.sin(angle)) + (y * math.cos(angle))
    
    return (newx,newy)

print("X1 rotated 35 degrees counter-clockwise:", rotateCCdegrees(1,3, 35))
print("X2 rotated 35 degrees counter-clockwise:", rotateCCdegrees(-1,5, 35))
print("X3 rotated 35 degrees counter-clockwise:", rotateCCdegrees(0,7, 35))

X1 rotated 35 degrees counter-clockwise: (-0.9015772647641463, 3.0310325692180213)
X2 rotated 35 degrees counter-clockwise: (-3.687034226044222, 3.5221837850939126)
X3 rotated 35 degrees counter-clockwise: (-4.015035054457322, 5.7340643100229425)


- Magnify the area by 4 times. [2 pts]

In [27]:
### Code Starts Here
def magnify4(x,y):
    return (x*4, y*4)
print("x1 magnified 4 times: ", magnify4(1,3))
print("x2 magnified 4 times: ", magnify4(-1,5))
print("x3 magnified 4 times: ", magnify4(0,7))


x1 magnified 4 times:  (4, 12)
x2 magnified 4 times:  (-4, 20)
x3 magnified 4 times:  (0, 28)


### Problem 3 [20 pts]
- Implement a function `mat_product` to calculate the matrix product of two n by n arrays. [8 pts] For example:


$A = \begin{bmatrix} 1 & 3 & 0 \\ 2 & 0 & 2 \\ 1 & 1 & 4 \end{bmatrix}$ and $A\cdot A=\begin{bmatrix} 7 & 3 & 6 \\ 4 & 8 & 8 \\ 7 & 8 & 18 \end{bmatrix}$

    mat_product(A,A)=?

In [28]:
### Code Starts Here
# Reference algorithm: https://www.geeksforgeeks.org/python-program-multiply-two-matrices/
# Reference: intialize result: https://www.geeksforgeeks.org/multiplication-two-matrices-single-line-using-numpy-python/#:~:text=Methods%20to%20multiply%20two%20matrices%20in%20python.%201.Using,and%20matrix2%20is%20a%20m%20x%20l%20matrix.
def mat_product(a, b):  
    result = [[0 for col in range(len(a))] for row in range(len(b[0]))]
    
    for i in range(len(a)):  
        for j in range(len(b[0])): 
            for k in range(len(b)): 
                result[i][j] += a[i][k] * b[k][j] 
    return result

- Test your code after generating two random 4 by 4 matrices, ${\bf X}$ and ${\bf Y}$. [4 pts]

In [29]:
### Test Starts Here
import numpy as np

randomArray1 = np.random.randint(10,size=(4,5))
randomArray2 = np.random.randint(10,size=(5,4))

a =    [[1,3,0], 
        [2,0,2], 
        [1,1,4]] 

print("Random matrix 1: \n",randomArray1)
print("Random matrix 2: \n",randomArray2)
print("Random matrix 1 * random matrix 2 \n", mat_product(randomArray1, randomArray2))
#print("Example A matrix * example A \n", mat_product(a, a))

Random matrix 1: 
 [[1 3 3 2 4]
 [3 7 3 7 6]
 [9 5 9 3 1]
 [2 6 8 0 8]]
Random matrix 2: 
 [[8 3 3 0]
 [3 0 6 0]
 [2 2 6 4]
 [9 7 3 7]
 [5 3 3 6]]
Random matrix 1 * random matrix 2 
 [[61, 35, 57, 50], [144, 82, 108, 97], [137, 69, 123, 63], [90, 46, 114, 80]]


- Inplement a function `mat_transpose` that transposes ${\bf X}$ and use the `mat_product` function to find the matrice of product: $Z={\bf X}^T\cdot{\bf Y}$ [8 pts]

        Z=mat_product(mat_transpose(X),Y)

In [30]:
### Code Starts Here
def mat_transpose(matrix):
    result = [[0 for col in range(len(matrix))] for row in range(len(matrix[0]))]
    
    for i in range(len(matrix)):
        for j in range(len(matrix[0])):
              result[j][i] = matrix[i][j]
    
    return result

a =    [[1,3,0], 
        [2,0,2], 
        [1,1,4]] 
a_transpose = mat_transpose(a)
z=mat_product(mat_transpose(a), a)
print(a)
print(a_transpose)
print(z)

[[1, 3, 0], [2, 0, 2], [1, 1, 4]]
[[1, 2, 1], [3, 0, 1], [0, 2, 4]]
[[6, 4, 8], [4, 10, 4], [8, 4, 20]]


### Problem 4 [30 pts]
- In this question, we will use the csv file **Temp.csv**. This question task is a process of exploratory data ansysis (EDA) to learn about data itself. Read it into a data frame, call it `Temp`. (Import the packages you think you need). [4 pts]

In [31]:
### Code Starts Here
import pandas as pd

Temp = pd.read_csv('Temp.csv')
Temperature = pd.read_csv('Temp.csv')

print(Temp)

         City        State  Temperature
0         NYC     New York           67
1      Albany     New York           49
2     Buffalo     New York           38
3    Hartford  Connecticut           63
4  Bridgeport  Connecticut           58
5      Treton   New Jersey           72
6      Newark   New Jersey           68


- We learned that the temperature at New Haven, Connecticut is currently 58 degree fahrenheit. Add this information into the DataFrame.[4 pts]

In [32]:
### Code Starts Here

Temp = Temp.append(pd.DataFrame({'City':['New Haven'], 
                                 'State':['Connecticut'],
                                 'Temperature':[58],
                                }))
print(Temp)

         City        State  Temperature
0         NYC     New York           67
1      Albany     New York           49
2     Buffalo     New York           38
3    Hartford  Connecticut           63
4  Bridgeport  Connecticut           58
5      Treton   New Jersey           72
6      Newark   New Jersey           68
0   New Haven  Connecticut           58


- Replace the names of the states by their abbreviations. [4 pts] That is 
    - Connecticut --> CT
    - New Jersey  --> NJ
    - New York    --> NY

In [33]:
### Code Starts Here
Temp = Temp.replace(to_replace ="New York", 
                 value  ="NY") 
Temp = Temp.replace(to_replace ="Connecticut", 
                 value  ="CT") 
Temp = Temp.replace(to_replace ="New Jersey", 
                 value  ="NJ") 

print(Temp)

         City State  Temperature
0         NYC    NY           67
1      Albany    NY           49
2     Buffalo    NY           38
3    Hartford    CT           63
4  Bridgeport    CT           58
5      Treton    NJ           72
6      Newark    NJ           68
0   New Haven    CT           58


- Select the rows in New York. [2 pts]

In [34]:
### Code Starts Here
tempNY = Temp[Temp['State'] == 'NY']

print(tempNY)

      City State  Temperature
0      NYC    NY           67
1   Albany    NY           49
2  Buffalo    NY           38


- What is the average of the temperature of cities in NY? [4 pts]

In [35]:
### Code Starts Here
temp_NY = Temp.loc[Temp['State'] == 'NY']
mean_temp_NY = temp_NY['Temperature'].mean()

print(mean_temp_NY)


51.333333333333336


- Find the mean and the standard deviation of the temperature of each state. [4 pts]

In [36]:
### Code Starts Here
temp_NY = Temp.loc[Temp['State'] == 'NY']
mean_temp_NY = temp_NY['Temperature'].mean()
std_temp_NY = temp_NY['Temperature'].std()


print("mean temp New York: ", mean_temp_NY)
print("std temp New York: ", std_temp_NY)

temp_NJ = Temp.loc[Temp['State'] == 'NJ']
mean_temp_NJ = temp_NJ['Temperature'].mean()
std_temp_NJ = temp_NJ['Temperature'].std()

print("mean temp New Jersey: ", mean_temp_NJ)
print("std temp New Jersey: ", std_temp_NJ)

temp_CT = Temp.loc[Temp['State'] == 'CT']
mean_temp_CT = temp_CT['Temperature'].mean()
std_temp_CT = temp_CT['Temperature'].std()

print("mean temp Connecticut: ", mean_temp_CT)
print("std temp Connecticut: ", std_temp_CT)

mean temp New York:  51.333333333333336
std temp New York:  14.6401275039985
mean temp New Jersey:  70.0
std temp New Jersey:  2.8284271247461903
mean temp Connecticut:  59.666666666666664
std temp Connecticut:  2.8867513459481287


- Create a data frame `Capital`, with two columns: State and Capital. [4 pts] 

    We know the capital of each state: 
    - Connecticut --> Hartford
    - New Jersey  --> Treton
    - New York    --> Albany
    
|| State| Capital|
| :-: |:---: | :---:|
| 0| CT  | Hartford|
| 1| NJ | Treton|
| 2| NY| Albany|

In [37]:
### Code Starts Here
capitalData = {'State':   ['CT', 'NJ', 'NY'],
               'Capital': ['Hartford', 'Treton', 'Albany']
               }

Capital = pd.DataFrame(capitalData, columns = ['State', 'Capital'])

print(Capital)

  State   Capital
0    CT  Hartford
1    NJ    Treton
2    NY    Albany


- Mutate a new boolean column, `Capital`, to `Temp`, which is `True` if the city in the row is the capital of the state, else `False`. [4 pts]

In [38]:
### Code Starts Here
# Inspired from: https://stackoverflow.com/questions/50518607/mutate-column-conditionally; https://thispointer.com/pandas-check-if-a-value-exists-in-a-dataframe-using-in-not-in-operator-isin/

Temp = Temp.assign(Capital = [True if Capital.isin([b]).any().any() else False for b in Temp['City']])


print(Temp)

         City State  Temperature  Capital
0         NYC    NY           67    False
1      Albany    NY           49     True
2     Buffalo    NY           38    False
3    Hartford    CT           63     True
4  Bridgeport    CT           58    False
5      Treton    NJ           72     True
6      Newark    NJ           68    False
0   New Haven    CT           58    False


### Problem 5 [30 pts]

- a. Load the Gross Domestic Product data for the 190 ranked countries in the file **GDP.csv**. Load **Country.csv** into a DataFrame. [6 pts]

In [1]:
### Code Starts Here
import pandas as pd

GDP_df = pd.read_csv('GDP.csv', skiprows=4) # Skipping header
Country_df = pd.read_csv('Country.csv')

# Naming unnamed columns
GDP_df.rename(columns={'Unnamed: 0':'CountryCode'}, inplace=True )
GDP_df.rename(columns={'Unnamed: 1':'Ranking'}, inplace=True )
GDP_df.rename(columns={'Unnamed: 3':'Full Name'}, inplace=True )
GDP_df.rename(columns={'Unnamed: 4':'GDP'}, inplace=True )

GDP_df['GDP'] = GDP_df['GDP'].str.replace(',', '') # Strip commas from GDP field

#GDP_df.drop(columns=['Unnamed: 2', 'Unnamed: 5', 'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9'])
del GDP_df['Unnamed: 2']
del GDP_df['Unnamed: 5']
del GDP_df['Unnamed: 6']
del GDP_df['Unnamed: 7']
del GDP_df['Unnamed: 8']
del GDP_df['Unnamed: 9']

print(GDP_df)

    CountryCode Ranking      Full Name         GDP
0           USA       1  United States   16244600 
1           CHN       2          China    8227103 
2           JPN       3          Japan    5959718 
3           DEU       4        Germany    3428131 
4           FRA       5         France    2612878 
..          ...     ...            ...         ...
321         NaN     NaN            NaN         NaN
322         NaN     NaN            NaN         NaN
323         NaN     NaN            NaN         NaN
324         NaN     NaN            NaN         NaN
325         NaN     NaN            NaN         NaN

[326 rows x 4 columns]


- b. Match the data based on the country shortcode. How many of the IDs match? [6 pts]

In [2]:
### Code Starts Here

#print(GDP_df)
#Country_df.head()

inner_join_df = pd.merge(GDP_df, Country_df, on='CountryCode', how='inner')

num_rows = inner_join_df.shape[0]

print("There are" , num_rows , "merged rows.")

There are 224 merged rows.


- c. Sort the data frame in descending order by GDP rank. What is the 13th country in the resulting data frame? (Note: GDP formats as 123,456,789.) [6 pts]

In [3]:
### Code Starts Here

inner_join_df["Ranking"] = pd.to_numeric(inner_join_df["Ranking"], errors='coerce') # Converting string ranking number to float type, for proper sorting
inner_join_df["GDP"] = pd.to_numeric(inner_join_df["GDP"], errors='coerce') # Converting GDP to number, for proper sorting

# Sort by Ranking or GDP???

#sorted_inner_join = inner_join_df.sort_values('GDP', ascending=False)
sorted_inner_join = inner_join_df.sort_values('Ranking', ascending=False)
#sorted_inner_join.to_csv('test.csv')
sorted_inner_join.to_csv('test1.csv')
print(sorted_inner_join.iloc[12]) # Using number 12 because iloc starts counting from 0

CountryCode                                                                GRD
Ranking                                                                  178.0
Full Name                                                              Grenada
GDP                                                                      767.0
Long Name                                                              Grenada
Income Group                                               Upper middle income
Region                                               Latin America & Caribbean
Lending category                                                         Blend
Other groups                                                               NaN
Currency Unit                                            East Caribbean dollar
Latest population census                                                  2001
Latest household survey                                                    NaN
Special Notes                                       

- d. What is the average GDP for the "High income: OECD" and "High income: nonOECD" group? [6 pts]

In [44]:
### Code Starts Here

high_income_OECD = inner_join_df.loc[inner_join_df['Income Group'] == 'High income: OECD']
high_income_nonOECD = inner_join_df.loc[inner_join_df['Income Group'] == 'High income: nonOECD']

#print(high_income_OECD)
#print(high_income_nonOECD)

mean_high_income_OECD = pd.to_numeric(high_income_OECD['GDP'], errors = 'coerce').mean()
mean_high_income_nonOECD = pd.to_numeric(high_income_nonOECD['GDP'], errors = 'coerce').mean()

print("Mean high income OECD: ", mean_high_income_OECD)
print("Mean high income nonOECD: ", mean_high_income_nonOECD)




Mean high income OECD:  1483917.1333333333
Mean high income nonOECD:  104349.82608695653


- e. What is the average GDP for different income groups and regions? [6 pts]

In [40]:
### Code Starts Here
#print(inner_join_df['Income Group'].unique())
#print(inner_join_df['Region'].unique())

high_income_OECD = inner_join_df.loc[inner_join_df['Income Group'] == 'High income: OECD']
high_income_nonOECD = inner_join_df.loc[inner_join_df['Income Group'] == 'High income: nonOECD']
upper_middle_income = inner_join_df.loc[inner_join_df['Income Group'] == 'Upper middle income']
lower_middle_income = inner_join_df.loc[inner_join_df['Income Group'] == 'Lower middle income']
low_income = inner_join_df.loc[inner_join_df['Income Group'] == 'Low income']

north_america = inner_join_df.loc[inner_join_df['Region'] == 'North America']
east_asia = inner_join_df.loc[inner_join_df['Region'] == 'East Asia & Pacific']
europe = inner_join_df.loc[inner_join_df['Region'] == 'Europe & Central Asia']
latin_america = inner_join_df.loc[inner_join_df['Region'] == 'Latin America & Caribbean']
south_asia = inner_join_df.loc[inner_join_df['Region'] == 'South Asia']
middle_east = inner_join_df.loc[inner_join_df['Region'] == 'Middle East & North Africa']
sub_saharan_africa = inner_join_df.loc[inner_join_df['Region'] == 'Sub-Saharan Africa']

mean_high_income_OECD = pd.to_numeric(high_income_OECD['GDP'], errors = 'coerce').mean()
mean_high_income_nonOECD = pd.to_numeric(high_income_nonOECD['GDP'], errors = 'coerce').mean()
mean_upper_middle_income = pd.to_numeric(upper_middle_income['GDP'], errors = 'coerce').mean()
mean_lower_middle_income = pd.to_numeric(lower_middle_income['GDP'], errors = 'coerce').mean()
mean_upper_low_income = pd.to_numeric(low_income['GDP'], errors = 'coerce').mean()

mean_north_america = pd.to_numeric(north_america['GDP'], errors = 'coerce').mean()
mean_east_asia = pd.to_numeric(east_asia['GDP'], errors = 'coerce').mean()
mean_europe = pd.to_numeric(europe['GDP'], errors = 'coerce').mean()
mean_latin_america = pd.to_numeric(latin_america['GDP'], errors = 'coerce').mean()
mean_south_asia = pd.to_numeric(south_asia['GDP'], errors = 'coerce').mean()
mean_middle_east = pd.to_numeric(middle_east['GDP'], errors = 'coerce').mean()
mean_sub_saharan_africa = pd.to_numeric(sub_saharan_africa['GDP'], errors = 'coerce').mean()

print("Mean GDP High Income OECD: ", mean_high_income_OECD)
print("Mean GDP High Income nonOECD: ", mean_high_income_nonOECD)
print("Mean GDP Upper Middle Income: ", mean_upper_middle_income)
print("Mean GDP Lower Middle Income: ", mean_lower_middle_income)
print("Mean GDP Upper Low Income: ", mean_upper_low_income)
print("Mean GDP North America: ", mean_north_america)
print("Mean GDP East Asia & Pacific: ", mean_east_asia)
print("Mean GDP Europe & Central Asia: ", mean_europe)
print("Mean GDP Latin America & Caribbean: ", mean_latin_america)
print("Mean GDP South Asia: ", mean_south_asia)
print("Mean GDP Middle East & North Africa: ", mean_middle_east)
print("Mean GDP Sub-Saharan Africa: ", mean_sub_saharan_africa)

Mean GDP High Income OECD:  1483917.1333333333
Mean GDP High Income nonOECD:  104349.82608695653
Mean GDP Upper Middle Income:  231847.84444444443
Mean GDP Lower Middle Income:  256663.4814814815
Mean GDP Upper Low Income:  14410.783783783783
Mean GDP North America:  6023832.666666667
Mean GDP East Asia & Pacific:  676834.4137931034
Mean GDP Europe & Central Asia:  427270.1
Mean GDP Latin America & Caribbean:  165881.2857142857
Mean GDP South Asia:  285761.625
Mean GDP Middle East & North Africa:  181992.88888888888
Mean GDP Sub-Saharan Africa:  28537.58695652174
